apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: betterwellness-config
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: betterwellness-config
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: betterwellness-config
        property: MONGODB_URI
    - secretKey: COGNITO_REGION
      remoteRef:
        key: betterwellness-config
        property: COGNITO_REGION
    - secretKey: COGNITO_USER_POOL_ID
      remoteRef:
        key: betterwellness-config
        property: COGNITO_USER_POOL_ID
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: betterwellness-config
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: betterwellness-config
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: betterwellness-config
        property: AWS_REGION
    - secretKey: SES_EMAIL
      remoteRef:
        key: betterwellness-config
        property: SES_EMAIL
    - secretKey: SQS_QUEUE_URL
      remoteRef:
        key: betterwellness-config
        property: SQS_QUEUE_URL
    - secretKey: REDIS_HOST
      remoteRef:
        key: betterwellness-config
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: betterwellness-config
        property: REDIS_PORT
